version: '3.9'
networks:
  fresns:
    driver: bridge
volumes:
  app:
  db_data:
  redis_data:
services:
  fresns:
    build:
      context: ./fresns
      args:
        - APP_PATH=${APP_PATH}
        - USER=www-data
      dockerfile: Dockerfile
    image: fresns
    container_name: fresns
    restart: unless-stopped
    working_dir: ${APP_PATH}
    volumes:
      - ${LOCAL_FILE_PATH}:${APP_PATH}
    networks:
      - fresns
    depends_on:
      - db
      - redis
    
    # mysql
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql
    container_name: fresns_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - fresns
    # redis
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis
    container_name: fresns_redis
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - fresns
  
  nginx:
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=true
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    restart: unless-stopped
    container_name: fresns_nginx
    volumes:
      - ${LOCAL_FILE_PATH}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - fresns
    networks:
      - fresns

    

    